name: "[Site] Check Pull Requests"

on:
    pull_request:
        branches:
            - site

concurrency:
    group: github-pages
    cancel-in-progress: false

permissions:
    contents: read
    pull-requests: write

jobs:
    check-pull-request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/dependency-review-action@v4
              with:
                  config-file: "./.github/dependency-review-config.yaml"
